# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecom < Formula
  desc "kubecom is terminal UI for easy interaction with Kubernetes"
  homepage "https://github.com/AnatolyRugalev/kube-commander"
  version "0.5.5-rc.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/<repo_owner>/<repo_name>/releases/download/0.5.5-rc.2/kubecom_0.5.5-rc.2_darwin_amd64.tar.gz"
    sha256 "3a7ba817a11b03348c3a1142eede7720253e5644db3a93d43f90f6300896c3c5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/<repo_owner>/<repo_name>/releases/download/0.5.5-rc.2/kubecom_0.5.5-rc.2_linux_amd64.tar.gz"
      sha256 "89b250a556e4f78fc0e7aa6dd85879e080954ce5f7a1eb7dd01d95a3eab22e6b"
    end
  end
  
  depends_on "kubectl"

  def install
    bin.install "kubecom"
  end
end
