# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecom < Formula
  desc "kubecom is terminal UI for easy interaction with Kubernetes"
  homepage "https://github.com/AnatolyRugalev/kube-commander"
  version "0.6.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/AnatolyRugalev/kube-commander/releases/download/0.6.2/kubecom_0.6.2_darwin_amd64.tar.gz"
    sha256 "8a7e0ca09f8963efc734c492394adef1e47feaada2986a68ec119efe97854e78"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/AnatolyRugalev/kube-commander/releases/download/0.6.2/kubecom_0.6.2_linux_amd64.tar.gz"
      sha256 "2632eb09e5dbad6e6e4af791d53fc0b2f01786ed2f5a8b29ad1d6984b610a17a"
    end
  end
  
  depends_on "kubectl"

  def install
    bin.install "kubecom"
  end
end
